Repository Team-OMD/Frontend, pull requests merged in 2024-05, with the labels that each got.

#61 [feat/#60] 좋아요 추가 기능구현
  src/api/Favorite.ts
  src/api/User.ts
  src/page/Mypage.tsx
  src/page/SetupBoard.tsx
  src/types/User.ts
  src/types/type.ts
Labels: 기능구현

#66 [feat/#53] 게시글 상품 등록 수정 삭제
  src/components/ProductModal.tsx
  src/page/PostDetail.tsx
  src/page/Post_fix.tsx
  src/page/Post_registration.tsx
  src/page/SetupBoard.tsx
  yarn.lock
Labels: 기능구현

#65 [chore/#63] Docker 설정
  Dockerfile
  docker-compose.dev.yml
  vite.config.ts
Labels: 환경설정

#68 [feat/#67] 상품 찜 기능구현
  src/App.tsx
  src/components/ProductModal.tsx
  src/page/PostDetail.tsx
  src/page/ProductDetail.tsx
Labels: 기능구현, 퍼블리싱

#70 [feat]상품 불러오기 및 조회 기능구현 완료
  package-lock.json
  src/components/Goodsitem.tsx
  src/page/GoodsBoard.tsx
  src/page/ProductDetail.tsx
  src/types/Product.ts
  yarn.lock
Labels: 기능구현

#71 [feat]이미지 등록 수정 / 썸네일 등록
  package.json
  src/page/PostDetail.tsx
  src/page/Post_fix.tsx
  src/page/Post_registration.tsx
  src/page/SetupBoard.tsx
  yarn.lock
Labels: 기능구현

#74 [Design/#62] 셋업 구성기능 구현(임시)
  src/api/Favorite.ts
  src/api/Setup.ts
  src/api/User.ts
  src/components/Dropdown.tsx
  src/components/GoodsModal.tsx
  src/page/GoodsBoard.tsx
  src/page/Home.tsx
  src/page/Mypage.tsx
  src/page/PostDetail.tsx
  src/page/Post_fix.tsx
  src/page/Post_registration.tsx
  src/page/ProductDetail.tsx
  src/page/SetupBoard.tsx
  src/types/type.ts
Labels: 기능구현, 퍼블리싱

#77 [design]상품상세페이지 가격표 정렬 및 가격 안나오는 문제 수정
  src/components/Goodsitem.tsx
  src/page/ProductDetail.tsx
Labels: 퍼블리싱

#79 [feat]이미지 업로드 방식 및 기타 수정
  package.json
  src/page/PostDetail.tsx
  src/page/Post_fix.tsx
  src/page/Post_registration.tsx
  src/page/SetupBoard.tsx
  yarn.lock
Labels: 기능구현, 오류수정

#82 [feat] 데스크탑 셋업 구성 기능구현 및 피드백 적용
  package.json
  src/components/Goodsitem.tsx
  src/components/ProductModal.tsx
  src/page/FavoriteBoard.tsx
  src/page/GoodsBoard.tsx
  src/page/Home.tsx
  src/page/Mypage.tsx
  src/page/PostDetail.tsx
  src/page/Post_fix.tsx
  src/page/SetupBoard.tsx
  src/types/type.ts
  yarn.lock
Labels: 기능구현, 퍼블리싱
