Repository Team-OMD/Frontend, pull requests merged in 2024-06, with the labels that each got.

#86 [feat]페이지네이션 구현
  src/page/GoodsBoard.tsx
  src/page/PostDetail.tsx
  src/page/Post_fix.tsx
  src/page/Post_registration.tsx
  src/page/ProductDetail.tsx
  src/page/SetupBoard.tsx
Labels: 기능구현, 퍼블리싱

#83 [design] 가격표 스크롤 처리 및 쉼표 처리
  src/components/Goodsitem.tsx
  src/page/GoodsBoard.tsx
  src/page/PostDetail.tsx
  src/page/ProductDetail.tsx
Labels: 퍼블리싱

#89 [feat]상품 검색 무한스크롤
  src/components/ProductModal.tsx
  src/page/PostDetail.tsx
  src/page/Post_fix.tsx
  src/page/Post_registration.tsx
Labels: 기능구현

#92 [fix/#91] 콘솔 로그 제거 및 디자인 수정
  src/api/User.ts
  src/components/GoodsModal.tsx
  src/components/Modal.tsx
  src/components/ProductModal.tsx
  src/page/Mypage.tsx
  src/page/PostDetail.tsx
  src/page/Post_fix.tsx
  src/page/Post_registration.tsx
  src/page/ProductDetail.tsx
Labels: 퍼블리싱, 오류수정
