Repository Team-OMD/Frontend, pull requests merged in 2024-04, with the labels that each got.

#31 [design/29] 게시물 상세 페이지 mui 적용 및 댓글창 수정
  package.json
  src/assets/Bookmark.png
  src/assets/ProfileImage.png
  src/assets/Share.png
  src/page/PostDetail.tsx
  yarn.lock
Labels: 퍼블리싱

#34 [design/#33] 인기 셋업상품 퍼블리싱 수정
  src/components/Navbar.tsx
  src/page/Home.tsx
Labels: 퍼블리싱

#35 [design/#30]마이페이지 디자인 수정
  src/assets/image/mypage/chat.svg
  src/assets/image/mypage/text.svg
  src/components/Dropdown.tsx
  src/page/Mypage.tsx
Labels: 퍼블리싱

#37 [design]게시글 등록 수정 페이지 수정
  src/page/Post_registration.tsx
Labels: 퍼블리싱

#42 [feat/#39] 로그인 및 회원가입 기능 구현
  package.json
  src/api/User.ts
  src/page/Login.tsx
  src/page/Signup.tsx
  src/types/User.ts
  yarn.lock
Labels: 기능구현

#43 [feat/#40] 게시글 목록 조회 기능구현
  package.json
  src/page/Mypage.tsx
  src/page/SetupBoard.tsx
  yarn.lock
Labels: 기능구현

#47 [feat/#45] 계정관리 기능구현
  package.json
  src/api/User.ts
  src/components/Modal.tsx
  src/page/Home.tsx
  src/page/Mypage.tsx
  src/store.ts
  yarn.lock
Labels: 기능구현

#49 [design/#48] 마이페이지 디자인 수정 및 좋아요한 게시물 전체보기 기능구현
  src/api/Favorite.ts
  src/components/Navbar.tsx
  src/page/FavoriteBoard.tsx
  src/page/GoodsBoard.tsx
  src/page/Home.tsx
  src/page/Mypage.tsx
  src/page/SetupBoard.tsx
  src/store.ts
  vite.config.ts
Labels: 기능구현, 퍼블리싱

#52 [feat]페이지네이션 , 게시글 에디터 적용
  package.json
  src/page/PostDetail.tsx
  src/page/Post_fix.tsx
  src/page/Post_registration.tsx
  src/page/SetupBoard.tsx
  vite.config.ts
  yarn.lock
Labels: 기능구현

#55 [feat] 게시글 등록 회원 연동
  src/page/Post_registration.tsx
Labels: 기능구현

#56 [feat] Home 페이지 HotDesk api 연동
  src/page/Home.tsx
Labels: 기능구현

#58 [feat/#57] 좋아요 기능구현
  src/api/Favorite.ts
  src/page/FavoriteBoard.tsx
  src/page/Mypage.tsx
  src/page/SetupBoard.tsx
Labels: 기능구현
